### ISSUE TITLE
Alterações

### ISSUE THREAD

**Issue by jennysson-junior** [Chinildo/Nivelamento#3]
Lembrei o motivo pelo qual eu não fiz diretamente por esse braço da API. caso insira um usuário inexistente, eu não sei como tratar o erro dessa forma e com a outra forma eu conseguia trata-lo.

**Comment by neetocode** [comment]
`GET /users/:username`

Então, quando ele acha o usuário o response vem com código de status `200` (Ok), quando o username passado não é encontrado vem com código de status `404` (Not Found)

Dê uma olhada
[https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status](url)
[https://httpstatuses.com/](url)
[https://developer.github.com/v3/users/#get-a-single-user](url)

**Comment by jennysson-junior** [comment]
Isso eu sei e os códigos de estado? Quando a resposta da erro também chega ao 4? Por que eu não tava conseguindo fazer pelo estado e muito menos com o try catch. No try catch até resolvia mas mostrava o erro no console

**Comment by neetocode** [comment]
Dê uma olhada aqui [https://developer.mozilla.org/pt-BR/docs/Web/API/XMLHttpRequest](url)
